<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MH_eETn' shared service.

return $this->privates['.service_locator.MH_eETn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'users' => ['privates', '.errored..service_locator.MH_eETn.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.MH_eETn": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'entityManager' => '?',
    'userRepo' => 'App\\Repository\\UserRepository',
    'users' => 'App\\Entity\\User',
]);
