<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.focPM19' shared service.

return $this->privates['.service_locator.focPM19'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'transRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
], [
    'serializer' => '?',
    'transRepository' => 'App\\Repository\\TransactionRepository',
]);
