<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fLPE55P' shared service.

return $this->privates['.service_locator.fLPE55P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'depotRepository' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'depotRepository' => 'App\\Repository\\CompteRepository',
    'serializer' => '?',
]);
