<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XfHROU8' shared service.

return $this->privates['.service_locator.XfHROU8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\PartenaireController::ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController::Depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController::ajoutcaissier' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController:Depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController:ajoutcaissier' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\PartenaireController::ajoutp' => '?',
    'App\\Controller\\UserController::Depot' => '?',
    'App\\Controller\\UserController::ajoutcaissier' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\PartenaireController:ajoutp' => '?',
    'App\\Controller\\UserController:Depot' => '?',
    'App\\Controller\\UserController:ajoutcaissier' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
