<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jNXpl_n' shared service.

return $this->privates['.service_locator.jNXpl_n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::contrat' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController::ajoutcompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\TransController::retrait' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\TransController::transaction' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController::Depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController::ajoutcaissier' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController::ajoutcomptuser' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController::bloquer' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UserController::bloquerdebloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:contrat' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController:ajoutcompte' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\TransController:retrait' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\TransController:transaction' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController:Depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\UserController:ajoutcaissier' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\UserController:ajoutcomptuser' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController:bloquer' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UserController:bloquerdebloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\ApiController::contrat' => '?',
    'App\\Controller\\PartenaireController::ajoutcompte' => '?',
    'App\\Controller\\PartenaireController::ajoutp' => '?',
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\TransController::retrait' => '?',
    'App\\Controller\\TransController::transaction' => '?',
    'App\\Controller\\UserController::Depot' => '?',
    'App\\Controller\\UserController::ajoutcaissier' => '?',
    'App\\Controller\\UserController::ajoutcomptuser' => '?',
    'App\\Controller\\UserController::bloquer' => '?',
    'App\\Controller\\UserController::bloquerdebloquer' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\ApiController:contrat' => '?',
    'App\\Controller\\PartenaireController:ajoutcompte' => '?',
    'App\\Controller\\PartenaireController:ajoutp' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\TransController:retrait' => '?',
    'App\\Controller\\TransController:transaction' => '?',
    'App\\Controller\\UserController:Depot' => '?',
    'App\\Controller\\UserController:ajoutcaissier' => '?',
    'App\\Controller\\UserController:ajoutcomptuser' => '?',
    'App\\Controller\\UserController:bloquer' => '?',
    'App\\Controller\\UserController:bloquerdebloquer' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
