<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEHqXZWl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEHqXZWl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEHqXZWl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEHqXZWl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEHqXZWl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EHqXZWl',
    'container.build_id' => 'aec9f4c3',
    'container.build_time' => 1567707689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEHqXZWl');
