<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmxSD0V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmxSD0V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMmxSD0V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMmxSD0V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMmxSD0V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MmxSD0V',
    'container.build_id' => 'fa9578c6',
    'container.build_time' => 1565358581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmxSD0V');
